biolib_version: 2
modules:
  main:
    image: 'local-docker://prediction-app:latest'
    command:'python3 predict.py'  # Command to run inside the container (environment)
    input_files:  # Where to put user input files inside the container
      - COPY / /
    output_files:  # Which output files or folders to return to the user from the container
      - COPY /predictions.csv / 

# Which input components to use in web based GUI for the app
arguments:
  - 
    default_value: sample.fasta
    description: 'Enter one or more proteins in FASTA format'
    key: '--fasta'
    key_value_separator: ' '
    required: true
    type: text-file
    
