# The .biolib/config.yml file tells Biolib how to interact with the Docker container
# Read more: https://biolib.com/docs/building-applications/syntax-of-config-yml/#modules-

biolib_version: 2

# Specify the name of your Docker image and its entrypoint (your app)
modules:
  main:
    working_directory: /home/biolib/
    image: 'local-docker://prediction-app:latest' # Name of locally built Docker image
    command: 'python3 /home/biolib/predict.py'  # Command to run inside the container (environment)
    input_files:  # Where to put user input files inside the container
      - COPY / /home/biolib/
    output_files:  # Which output files or folders to return to the user from the container
      - COPY /home/biolib/ / 

# Biolib.com app user-interface
# Read more: https://biolib.com/docs/building-applications/syntax-of-config-yml/#arguments
arguments:
  - 
    key: '--fasta'  # Our predict.py input argument
    description: 'Enter one or more proteins in FASTA format'
    key_value_separator: ' '
    default_value: /home/biolib/sample.fasta  # Example input file
    type: text-file # Required. Choose from: text, file, hidden, toggle, number, radio, dropbox, multiselect
    required: true # true or false (default true)

  - 
    # Optional: extra options
    # https://biolib.com/docs/building-applications/syntax-of-config-yml/#arguments
    key: '--model'
    type: toggle
    description: I love BioLib
    options:
          "on": "model1"
          "off": "model2"

# Optional: visualize outputs based on output file extension
# https://biolib.com/docs/building-applications/output/
main_output_file: /predictions.csv

# Optional: extra user interface options
# https://biolib.com/docs/building-applications/syntax-of-config-yml/#license_file
description_file: README.md # Renders README as markdown (default README.md). Also grabs images.
license_file: LICENSE # License in side-bar (default LICENSE)

# Optional: Citation field (left side-bar). Uses Bibtex but in YAML format.
# https://www.bibtex.com/g/bibtex-format/
citation:
    entry_type: misc
    author: Magnus Haraldson Høie, Mads Damgaard Pedersen and others
    title: prediction-app
    publisher: Biolib Research
    year: '2024'
