name: CI
on: push
jobs:
  CI:
    uses: biolibtech/biolib-github-templates/.github/workflows/app_build_and_push.yml@main
    secrets: inherit
    with:
      app-uri: BioLibDevelopment/prediction-app
      docker-tag: app-prediction